set $mod Mod4
set $term kitty
set $keyboard fcitx5
set $sp toggle_sp

bindsym $mod+Mod1+h exec bash -c 'swaymsg -t get_tree | grep -q toggle_sp && swaymsg "[con_mark=\"toggle_sp\"] scratchpad show, floating disable" || (swaymsg "mark toggle_sp" && swaymsg "move scratchpad")'

bindsym $mod+Return exec $term
bindsym $mod+q kill
bindsym $mod+Shift+c reload

bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+h focus left
bindsym $mod+l focus right
bindsym $mod+k focus up
bindsym $mod+j focus down

bindsym $mod+Ctrl+Shift+Left exec bash -c 'c=$(swaymsg -t get_workspaces|jq ".[]|select(.focused).num"); t=$([ "$c" -le 1 ] && echo 1 || echo $((c-1))); swaymsg move container to workspace $t; swaymsg workspace $t'

bindsym $mod+Ctrl+Shift+Right exec bash -c 'c=$(swaymsg -t get_workspaces|jq ".[]|select(.focused).num"); t=$((c+1)); swaymsg move container to workspace $t; swaymsg workspace $t'

bindsym $mod+Ctrl+Right exec bash -c 'c=$(swaymsg -t get_workspaces|jq ".[]|select(.focused).num"); t=$((c+1)); swaymsg workspace $t'

bindsym $mod+Ctrl+Left exec bash -c 'c=$(swaymsg -t get_workspaces|jq ".[]|select(.focused).num"); t=$([ "$c" -le 1 ] && echo 1 || echo $((c-1))); swaymsg workspace $t'

bindsym $mod+Shift+h move left
bindsym $mod+Shift+l move right 
bindsym $mod+Shift+k move up
bindsym $mod+Shift+j move down
bindsym $mod+Shift+Space floating toggle
bindsym Mod4+r mode resize
client.focused #1a1b26 #e0e0e0 #ffffff #e0e0e0 #e0e0e0
default_border pixel 5
mode "resize" {
  bindsym Escape mode default
  bindsym h resize shrink width 10 px
  bindsym j resize grow height 10 px
  bindsym k resize shrink height 10 px
  bindsym l resize grow width 10 px
}
bindsym $mod+Tab focus right
bindsym $mod+Shift+s exec bash -c 'FILE=~/Pictures/screenshot-$(date +%Y-%m-%d_%H-%M-%S).png; grim -g "$(slurp)" "$FILE" && wl-copy < "$FILE" && notify-send -t 2000 "Screenshot saved & copied" "$FILE"'

bindsym $mod+Space exec quickshell-launcher
bindsym $mod+Shift+w exec quickshell-wallpaper-selector
bindsym $mod+Ctrl+l exec quickshell-lock
floating_modifier Mod4 normal
bindsym XF86AudioMute exec pamixer -t
bindsym XF86AudioLowerVolume exec pamixer -d 5
bindsym XF86AudioRaiseVolume exec pamixer -i 5
bindsym XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym XF86MonBrightnessUp exec brightnessctl set +5%
gaps inner 5
gaps outer 5

output eDP-1 resolution 3840x2160@60Hz position 0,0 scale 2
output DP-1 resolution 2560x1440@75Hz position 1920,0 scale 1

exec --no-startup-id $term
exec --no-startup-id $keyboard
exec --no-startup-id mako
exec --no-startup-id quickshell --config launcher --no-duplicate
exec --no-startup-id waybar
exec_always --no-startup-id sh -c 'pkill -x autotiling 2>/dev/null || true; exec autotiling'

seat seat0 xcursor_theme Banana 32

input "9610:268:BY_Tech_Gaming_Keyboard" {
  xkb_options altwin:swap_alt_win
}


output * bg /etc/nixos/assets/wallpaper/wallhaven-3l6xw6.jpg fill
exec_always systemctl --user set-environment XDG_CURRENT_DESKTOP=sway

exec_always systemctl --user import-environment DISPLAY \
SWAYSOCK \
WAYLAND_DISPLAY \
XDG_CURRENT_DESKTOP

exec_always dbus-update-activation-environment --systemd DISPLAY \
SWAYSOCK \
WAYLAND_DISPLAY \
XDG_CURRENT_DESKTOP=sway

input type:touchpad {
  tap enabled
  natural_scroll enabled
  drag_lock disabled
}
